import React from "react";
import { motion } from "framer-motion";

const AuthenticationFeature = () => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 50 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, amount: 0.5 }}
      transition={{ duration: 0.2, ease: "easeOut" }}
      className="w-full flex flex-col md:flex-row items-center px-4 gap-2 py-10 text-gray-200 transition-all duration-300 ease-in-out"
    >
      <div className="flex items-center justify-center w-full md:w-1/2">
        <img
          src="/about/authentication.png"
          alt="Authentication Image"
          className="w-full about-image transition-transform duration-300 ease-in-out hover:scale-105"
        />
      </div>
      <div className="flex flex-col items-center justify-center w-full md:w-1/2 text-md md:text-xl px-2 md:px-14 gap-3">
        <h2 className="text-xl md:text-3xl font-semibold text-center">
          Two-Factor Authentication
        </h2>
        <p>
          CodeElevate uses a secure two-factor authentication (2FA) login
          process to keep user accounts highly secure, even if standard
          passwords are compromised. After the user enters the correct username
          and password, they must provide a time-based one-time password (TOTP)
          generated by an authenticator app.
        </p>
      </div>
    </motion.div>
  );
};

export default AuthenticationFeature;
